import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./Components/Shared/Navbar";
import NavigationLinks from "./Components/Shared/NavigationLinks";
import Footer from "./Components/Shared/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col min-h-screen"> 
          {/* Navbar */}
          <header className="border-b-[#A1D6B2] border-b-[1px] rounded-b-xl">
            <Navbar />
          </header>

          {/* Main Content */}
          <main className="flex flex-1 overflow-hidden">
            {/* Sidebar */}
            <aside className="w-52 h-full overflow-y-auto border-r pl-4 border-[#A1D6B2]">
              <NavigationLinks />
            </aside>

            {/* Main content */}
            <section className="w-full h-full overflow-y-auto">
              {children}
            </section>
          </main>

          {/* Footer */}
          <footer className="mt-auto"> 
            <Footer />
          </footer>
        </div>
      </body>
    </html>
  );
}

