import ReactQueryProvider from "@/Providers/ReactQueryProvider";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import AuthProvider from "@/Providers/AuthProvider";
import Root from "./Root/page";

// Metadata for SEO (server-side)
export const metadata = {
  title: "Web Query | Welcome To Our Website",
  description: "Generated by create next app",
};

// Server-side layout
export default async function RootLayout({children}) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <AuthProvider>
          <body
            className=''>
            <Toaster />
            <div>

              <Root>{children}</Root>

              </div>
          </body>
        </AuthProvider>
      </ReactQueryProvider>
    </html>
  );
}
